# Exercise 1

### In Python, we could deal with scientific data as a list

In [ ]:
my_list = [1,3,5,7,9,2,4,6,8]
print("The third element in my_list is " + str(my_list[2]))

### But for more complex operations over more complex data, this isn't super great.
### Say that I ran three experiments with results as follows.

In [ ]:
experiment_results = [[2,5,3,6,8,5,7,9,7,5,3,3], 
                      [1,3,2,4,6,5,7,8,9,8,4,3],
                      [4,3,5,4,6,8,7,11,9,7,4,1]]

### Now I want to show the average of the sixth measurement in each experiment

In [ ]:
sum_sixth_measurement = experiment_results[0][5] + experiment_results[1][5] + experiment_results[2][5]
mean_sixth_measurement = float(sum_sixth_measurement)/3
print("The mean sixth experiment result is "+ str(mean_sixth_measurement))

### And what about the mean value of the ninth?

In [ ]:
sum_ninth_measurement = experiment_results[0][8] + experiment_results[1][8] + experiment_results[2][8]
mean_ninth_measurement = float(sum_ninth_measurement)/3
print("The mean ninth experiment result is "+ str(mean_ninth_measurement))

### Gosh. I wish there was a better way to do this!

### Introducing Numpy!

### First, we use the "import" command to tell python that we want to load a new module

In [ ]:
import numpy 

### Second, I want to make a numpy-style array, so I use "numpy.array()". The input for numpy.array is a list of numbers that you want to turn into an array. 

### Printing the thing will show you what it looks like


In [ ]:
np_expt_res = numpy.array(experiment_results)
print(np_expt_res)

### I can pick elements from np_expt_res in a similar way to normal lists, except this time I can give two indices, because this is technically a 3x12 matrix
### To get the sixth result (remember, "sixth" means a python index of [5]) of the first experiment ([0]), I can just ask for element [0,5] of my numpy array.

In [ ]:
print("The sixth result of the first experiment is "+ str(np_expt_res[0,5]))

### I can also take "slices" of the numpy list in different directions. To do this, I leave one of the indices as a ":" instead of providing a value.

In [ ]:
print("The sixth result of each experiment is "+ str(np_expt_res[:,5]))
sixth_result_mean = numpy.mean(np_expt_res[:,5])
print("The mean of the sixth results is " + str(sixth_result_mean))
every_other_num = np_expt_res[0,::2] ##the zero calls the FIRST experiment (the first row in np_expt_res)
print("Every other result in the first experiment is " +str(every_other_num))

### EXERCISE: The last command returned the 1st, 3rd, 5th, etc... item from the list. Now I want the 2nd, 4th, 6th, etc. Add a print statement here to do that.

In [ ]:
every_other_other = '?'
#google slicing in numpy!
#print every other OTHER!
#write code here

# Exercise 2

### Here I'm using python's built-in list to hold a 3x3 matrix of numbers

In [ ]:
my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]
print("my_matrix is "+str(my_matrix))
print("The first row of my_matrix is "+ str(my_matrix[0]))
print("The top left item in my_matrix is "+ str(my_matrix[0][0]))
print("the first column of my_matrix is "+ str([str(my_matrix[0][0])+" "+str(my_matrix[1][0])+" "+str(my_matrix[2][0])]))

### EXERCISE: Add code here to add each number in the first row of my_matrix to the numbers below it (in the second row) and print the new row for the user. That is, this should return [5, 7, 9]. This will be pretty ugly.

In [ ]:
#code here

### Now I'll do the same thing as above, but using a numpy array.

In [ ]:
my_np_matrix = numpy.array(my_matrix)
print("my_np_matrix is")
print(my_np_matrix)
print("The first row of my_np_matrix is "+ str(my_np_matrix[0]))
print("The top left item in my_np_matrix is "+ str(my_np_matrix[0,0]))
print("the first column of my_np_matrix is "+ str(my_np_matrix[:,0]))

### omg that was, like, so easy
### EXERCISE: Same as previous, but with numpy: Add code here to add the numbers in the first row of my_np_matrix to the numbers in the second row and print them for the user. This should be a lot easier using a numpy array.

In [ ]:
#code code code

### EXERCISE: Add code to print the top left 2x2 matrix from my_np_matrix. Since the original matrix is 

    [[1 2 3]
    [4 5 6]]

 ### This should print:

    [[1 2]
    [4 5]]

In [ ]:
#your codey code here

### In numpy, I can also get a "mask" of positions in the matrix I like. A mask is a matrix with the same shape as the original, but wth either True or False in each position. I could say "which numbers in this matrix are divisible by 3?", and get a matrix back where the positions that are divisible by 3 are set to True, and those that aren't are set to False.
### (The "%" operation will return the remainder of a division. For example 5%3 will give the remainder of 5/3, or 2). The operation is called a "modulus", or "mod" for short. 


In [ ]:
my_truth_matrix = (my_np_matrix % 3 == 0)

### So now my_truth_matrix contains "True" and "False" entries corresponding to whether each element in my_np_matrix divides evenly by 3.

In [ ]:
print('The items in my_np_matrix that divide evenly by 3 are in these positions:')
print(my_truth_matrix)

### I can use this truth matrix as a different type of index for selecting parts of the original matrix

In [ ]:
print('Their values are '+ str(my_np_matrix[my_truth_matrix])) #CHECK IT OUT
## SO COOL
# MUCH COMPUTER 
# WOW

### EXERCISE: Add code here to do the same as above for all the items which are greater than 5

In [ ]:
##CODE CODE CODE

# Exercise 3

### Here I'm loading a file containing average attendance and ticket prices for different NBA teams (the team names aren't listed).

#### Note: Here we use some function called "numpy.genfromtxt()". Don't think that you need to know absolutely all of the vague little commands in numpy in order to use it - I only know about these commands because I use them very frequently. Same with the pyplot module that I use later in this example. I use both numpy and pyplot extensively in my work but have probably used less than 5% of any of their functions. 

#### Another note: When you approach data processing tasks, you should open the file in a text editor to see what the formatting looks like. Look for patterns like columns in simple cases or certain words or phrases that appear near values of interest in more complex data extraction work.

In [ ]:
pathToCSV = '/Users/abigaildommer/Desktop/BioChemCoRe-2018/numpyExercises/exercise3/NBA_attendance_price_simple.csv'
my_data = numpy.genfromtxt(pathToCSV, delimiter = ',')

### I'll put in a nice little message for the user to understand what they're seeing

In [ ]:
print("Average Attendance |  Ticket Price")
print(my_data)
##sooooo cute

### EXERCISE: Add code here to print out the average revenue for each team (the ticket price times the attendance). 
### The first number should be 280699.58 (from 13993 * 20.06)

In [ ]:
###codecodecodecodecode

### Now I'll import a simple plotting module called "matplotlib.pyplot" to help me show some data

In [ ]:
import matplotlib.pyplot as plt ##importing
%matplotlib inline 
##this line ^^ makes generated plots appear in jupyter notebooks so you can see what you're plotting

### I want to create a scatter plot of ticket price vs. attendance. The pylab.scatter command takes two lists of numbers - The first corresponds to the x values of the points, the second corresponds to the y values. 

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
plt.scatter(my_data[:,0], my_data[:,1])
# Be sure you understand what my_data[:,0] and my_data[:,1] are! 
##If you don't, you should add code to print out their values.

### We're missing axis labels YO
### you do the thing:

    fig = plt.figure()
    ax = fig.add_subplot(111)
    plt.scatter(my_data[:,0], my_data[:,1])
    ax.set_xlabel('thing')
    ax.set_ylabel('other thing')

In [ ]:
#do the thing here

### EXERCISE: Add code here to make a scatter plot of the average attendance vs. the total revenue that you calculated above. 